baseURL               = "https://eric.run.place/"
languageCode          = "zh-CN"
title                 = "Eric Cao - 个人页面"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"					# 站点静态文件保存目录


[params]
    author        = "Eric Cao"
    description   = "Eric Cao 的个人页面 - 展示个人信息、项目和联系方式"
    repository    = "https://github.com/caoergou/caoergou.github.io"
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "Eric's Page"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    nightMode     = false					# 默认站点为浅色模式
    yiyan         = true                    # 默认启用一言服务

[params.social]
    github        = "https://github.com/caoergou"
    twitter       = "https://twitter.com/eric_cao"
    email         = "eric@example.com"

[params.seo]
    baiduhmid       = ''	# 百度统计 hm.src 的 ID
    baiduSiteVer    = ''			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense

[params.images]
    favicon           = "assets/images/favicon.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; 2024 - ∞ Eric Cao <br/>'