name: "Submit a site"
description: Submit your site to Truer.ai.
title: "[SITE]"
labels: [
  "site"
]
body:
  - type: input
    id: site-url
    attributes:
      label: "Site URL"
      description: Please enter your website URL.
      placeholder: https://oepnai.com
    validations:
      required: true
  - type: input
    id: logo-url
    attributes:
      label: "Logo URL"
      description: Please enter your website Logo URL.
      placeholder: https://chat.openai.com/favicon-32x32.png
    validations:
      required: true
  - type: textarea
    id: short-description
    attributes:
      label: "short-description"
      description: Please enter an short description of your site
      placeholder: OpenAI's groundbreaking product: ChatGPT
    validations:
      required: true
  - type: dropdown
    id: kind
    attributes:
      label: "kind"
      description: Which kind does your site belong to ?
      multiple: true
      options:
        - Browser Plugin
        - Desktop App
        - Model
        - Web App
        - API
        - Paper
    validations:
      required: false